import React from "react";
import "../styles/Favebiz.scss";
import animateScrollTo from "animated-scroll-to";
import arrowDown from "../assets/arrow-down.png";
import faveMockup from "../assets/fave-mockup.png";
import Fade from "react-reveal";
import shape from "../assets/favebiz-shape.png";
import pencil from "../assets/favebiz-pencil.png";
import Footer from "../components/Footer";
import CountUp from "react-countup";

const technologies = ["HTML5", "SASS", "JavaScript", "React", "Ruby", "AWS"];

const TechnologyCards = () => {
  let temp = [];

  technologies.forEach(technology => {
    temp.push(
      <div className="technology" key={technology}>
        {technology}
      </div>
    );
  });

  return temp;
};
const Favebiz = () => {
  return (
    <React.Fragment>
      <div className="favebiz-banner">
        <div className="textbox">
          <Fade cascade>
            <h1>FaveBiz</h1>
          </Fade>

          <Fade cascade>
            <p>By Fave Group</p>
          </Fade>
        </div>

        <div
          className="arrow-div"
          onClick={() => {
            animateScrollTo(document.querySelector(".favebiz-text"));
          }}
        >
          <p>Scroll Down</p>
          <img src={arrowDown} className="arrow-down" alt="arrow" />
        </div>
      </div>

      <div className="favebiz-text">
        <Fade bottom>
          <h1 className="favebiz-textbox">
            FaveBiz enables you to view analytics generated by millions of
            active users.
          </h1>
        </Fade>
      </div>
      <div className="fave-mockup-div">
        <img src={faveMockup} className="fave-mockup" alt="mockup" />
      </div>
      <div className="problem-solution">
        <Fade>
          <div className="problem">
            <div className="img-div">
              <img src={shape} alt="problem" />
            </div>
            <h1>The problem</h1>
            <p>
              Prior to development, FaveBiz was operating on different
              frameworks and sites that clashed in functionality. This led to a
              poorer user experience.
            </p>
          </div>
        </Fade>
        <Fade>
          <div className="solution">
            <div className="img-div">
              <img src={pencil} alt="solution" />
            </div>
            <h1>The solution</h1>
            <p>
              Our team of web and full-stack developers designed and developed a
              responsive web app that revolves around clean design + code that
              makes understanding the app less of a challenge. Our users can now
              focus more on what matters most.
            </p>
          </div>
        </Fade>
      </div>

      <Fade right>
        <div className="active-users">
          <p>Active users</p>
          <h1>
            <CountUp separator=" " duration={5} end={4000000} /> +
          </h1>
        </div>
      </Fade>

      <Fade left>
        <div className="technologies-used">
          <TechnologyCards />
        </div>
      </Fade>

      <Footer />
    </React.Fragment>
  );
};

export default Favebiz;
